config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  get 'pending' => 'users#pending'

  resources :events do
    member do
      get :all_orders
      get :agg_orders
    end
  end
  resources :eventers
  resources :orders
  resources :orderitems
  resources :users do
    member do
      get :order_list
      get :usericon
    end
  end

scope '/admin' do
  get 'approve' => 'admin#approve'
  put 'approve_user/:id' => 'admin#approve_user'
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [:pending]
  before_action :pending_user?, :except => [:pending]
  include UsersHelper

  def index
    @users = User.all
  end

  def register
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end
  
  def usericon
    @user = User.find(params[:id])
    render :layout => false
  end

  def order_list
    @orders = Order.where(user_id: params[:id])
    @orders_courier = Order.where(courier_id: params[:id])
    @name = get_user_name(params[:id])
  end

  def pending
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_user_name (user_id = 0)
    User.find(user_id).name
  rescue ActiveRecord::RecordNotFound
    "None"
  end
end

app/views/users/index.html.erb
<h3>Users</h3>
<table class="table">
<tr>
  <th>Name</th>
  
  <th></th>
</tr>
<% @users.each do |user| %>
<tr>
  <td><%= user.name %></td>
  
  <td><%= link_to "Orders", order_list_user_path(user.id), :class => "btn btn-sm btn-primary" %></td>
</tr>
<% end %>
</table>

app/views/users/order_list.html.erb
<h3>Orders created by <%= @name %></h3>
<table class="table">
<tr>
  <th>Order Number</th>
  <th>Event Name</th>
  <th>Total Price</th>
  <th></th>
</tr>
<% @orders.each do |order| %>
<tr>
  <td><%= order.id %></td>
  <td><%= link_to get_event_name(order.event_id), event_path(order.event_id) %></td>
  <td><%= format_price(order.event_id, get_order_total(order['id'])) %></td>
  <td><%= link_to "View Order", order_path(order['id']), :class => "btn-sm btn-primary" %></td>
</tr>
<% end %>
</table>
<% if not @orders_courier.empty? %>
<h3>Orders couriered by <%= @name %></h3>
<table class="table">
<tr>
  <th>Order Number</th>
  <th>Who</th>
  <th>Event Name</th>
  <th>Total Price</th>
  <th></th>
</tr>
<% @orders_courier.each do |order| %>
<tr>
  <td><%= order.id %></td>
  <td><%= link_to get_user_name(order.user_id), order_list_user_path(order.user_id) %></td>
  <td><%= link_to get_event_name(order.event_id), event_path(order.event_id) %></td>
  <td><%= format_price(order.event_id, get_order_total(order['id'])) %></td>
  <td><%= link_to "View Order", order_path(order['id']), :class => "btn-sm btn-primary" %></td>
</tr>
<% end %>
</table>
<% end %>

app/views/users/pending.html.erb
Approval Pending.

app/views/users/show.html.erb
<%= @user.name %>

app/views/users/usericon.html.erb
<%= @user.name %>