config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  get 'pending' => 'users#pending'

  resources :events do
    member do
      get :all_orders
      get :agg_orders
    end
  end
  resources :eventers
  resources :orders
  resources :orderitems
  resources :users do
    member do
      get :order_list
      get :usericon
    end
  end

scope '/admin' do
  get 'approve' => 'admin#approve'
  put 'approve_user/:id' => 'admin#approve_user'
end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :items
  has_many :orders
  has_many :eventers
  accepts_nested_attributes_for :items, allow_destroy: true
  validates :currency, length: { is: 3 }, format: { with: /\A[A-Z]{3}\z/}
  
  def cur_prefix
    case self.currency
    when "JPY"
      '¥'
    when "GBP"
      '£'
    when "EUR"
      '€'
    else
      '$'
    end
  end
    
  def cur_precision
    case self.currency
    when "JPY"
      0
    else
      2
    end
  end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :pending_user? 

  # list of supported currencies
  before_filter :set_currencies
  
  def set_currencies
    @currencies = ['JPY', 'USD', 'CAD', 'SGD', 'GBP', 'EUR', 'HKD']
  end
  
  def index
    @events = Event.all.order(date: :desc)
  end

  def show
    @event = Event.find(params[:id])
    @items = Item.where(event_id: params[:id])
    @order = Order.new
    @eventers = Eventer.where(event_id: params[:id]).where.not(event_status: Eventer.event_statuses[:notgoing])
    @userevent = @eventers.where(user_id: current_user.id).first
    
  end

  def new
    @event = Event.new
  end

  def create
    new_event = Event.new
    new_event.name = params[:event][:name]
    new_event.location = params[:event][:location]
    new_event.date = params[:event][:date]
    new_event.url = params[:event][:url]
    new_event.currency = params[:event][:currency]
    begin
      new_event.save
    rescue
      puts "failed"
    end
    redirect_to :controller => :events, :action => :index
  end

  def edit
    @event = Event.find(params[:id])
    @items = Item.where(event_id: params[:id])
    @currencies
  end

  def update
    p params[:id]
    event = Event.find(params[:id])
    event.name = params[:event][:name]
    event.location = params[:event][:location]
    event.date = params[:event][:date]
    event.currency = params[:event][:currency]
    event.save

    items = params[:event][:items_attributes]
    p items
    items.each do |item|
      item = item.last
      # Add Item if doesn't exist
      if item['id'].nil?
        Item.new(event_id: params[:id], name: item['name'], description: item['description'], price: item['price']).save
      else
        if item['_destroy']
          Item.find(item['id']).destroy
          Orderitem.where(item_id: item['id']).destroy_all
          next
        else
          update_item = Item.find(item['id'])
          update_item.update_attributes(name: item['name'], description: item['description'], price: item['price'])
        end
      end
    end
    redirect_to event_path(params[:id])
  end

  def all_orders
    @event = Event.find(params[:id])
    @orders = Order.where(event_id: params[:id])
  end

  def agg_orders
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def get_event_name(event_id)
    Event.find(event_id).name
  end
  
  def format_price(event_id, value)
    _event = Event.find(event_id)
    number_to_currency(value, unit: _event.cur_prefix, precision: _event.cur_precision )
  end
  
end

app/views/events/_event.html.erb
<div class="event md-col-12">
  <span class="event-content">
    <% if event.date - Time.now < 0 %>
    <span class="label-date old"><%= event.date.to_date %></span>
    <% else %>
    <span class="label-date"><%= event.date.to_date %></span>
    <% end %>
    <span class="label-name"><%= link_to event.name, :action => :show, :id => event.id %></span>
    <span class="event-location">@ <%= event.location %></span>
  </span>
  <span class="event-menu">
    <%= link_to content_tag(:span, nil, :class => "glyphicon glyphicon-eye-open"), event_path(event.id), :class => "btn btn-sm btn-primary" %>
    <%= link_to content_tag(:span, nil, :class => "glyphicon glyphicon-align-justify"), all_orders_event_path(event.id), :class => "btn btn-sm btn-primary" %>
    <%= link_to content_tag(:span, nil, :class => "glyphicon glyphicon-credit-card"), agg_orders_event_path(event.id), :class => "btn btn-sm btn-primary" %>
  </span>
</div>

app/views/events/_event_menu.html.erb
<%= link_to "Edit Event", edit_event_path(@event.id), :class => "btn btn-sm btn-success" %>
<%= link_to "Orders", all_orders_event_path(@event.id), :class => "btn btn-sm btn-primary" %>
<%= link_to "Purchase List", agg_orders_event_path(@event.id), :class => "btn btn-sm btn-primary" %>
<%= link_to "Event Link", @event.url , :class => "btn btn-sm btn-info" if !@event.url.nil?%>

app/views/events/_items_edit.html.erb
  
    <td><%= item_form.remove_nested_fields_link "", :class => 'btn btn-sm btn-danger glyphicon glyphicon-minus' %></td>
    <td><%= item_form.text_field :name, :required => true, class: 'form-control' %></td>
    <td><%= item_form.text_field :description , class: 'form-control' %></td>
    <td class="col-numeric col-price"><%= item_form.number_field :price, :required => true , class: 'form-control' %></td>

app/views/events/_order_menu.html.erb
<%= link_to "View Event", event_path(@event.id), :class => "btn btn-sm btn-primary" %>
<%= link_to "View Orders", all_orders_event_path(@event.id), :class => "btn btn-sm btn-primary" %>
<%= link_to "View Purchase List", agg_orders_event_path(@event.id), :class => "btn btn-sm btn-primary" %>
<%= link_to "Event Link", @event.url , :class => "btn btn-sm btn-info" if !@event.url.nil?%>

app/views/events/agg_orders.html.erb
<div class="maincontainer">
  <div class="title">
    <h3>Purchase list for [<%= @event.date.to_date %>] <%= @event.name %> @ <%= @event.location %></h3>
  </div>
<% @event.items.each do |item| %>
    <% if item.orderitems.sum(:quantity) > 0 %>
      <%= render "items/agg_item", :item => item, :quantity => item.orderitems.sum(:quantity) %>
    <% end %>
  <% end %>
</div>

app/views/events/all_orders.html.erb
<div class=""><h3>All Orders by [<%= @event.date.to_date %>] <%= @event.name %> @ <%= @event.location %></h3></div>
<%= render "order_menu" %>
<% @orders.each do |order| %>
  <table class="table table-striped">
    <tr>
      <h3><%= get_user_name(order.user_id) %></h3>
      <ul>
        <li>Courier: <%= get_user_name order.courier_id %></li>
        <li>
            <% if order.courier_id != current_user.id %>
                <%= link_to "Assign Self as Handler", order_path(order.id, :courier_id => current_user.id), :method => :put, :class => "btn btn-sm btn-primary" %>
            <% else %>
               <%= link_to "Unassign Self as Handler", order_path(order.id, :courier_id => 0), :method => :put, :class => "btn btn-sm btn-primary" %>
            <% end  %>
            
          </li>
      </ul>
    </tr>
    <%= render "orders/item_header" %>
    <% order.orderitems.each do |orderitem| %>
      <%= render "orders/item", :orderitem => orderitem %>
    <% end %>
    <%= render "orders/order_total", :order_id => order.id, :order => order %>
  </table>
<% end %>

app/views/events/edit.html.erb
<%= form_for @event, :url => {:action => :update, :controller => :events }, :html => {:class => 'form-inline'} do |f| %>
<div><h3>
<%= f.text_field :date, :value => @event.date.strftime("%Y-%m-%d"), :required => true, :class => "datepicker form-control" %>
<%= f.text_field :name, :required => true, :class => "form-control" %>
<span class="form-group">@ <%= f.text_field :location, :required => true, :class => "form-control" %></span></h3></div>
<%= hidden_field_tag :event_id, @event.id %>
<table class="table">
<thead>
<tr>
  <th class="col-delete">Delete</th>
  <th class="col-name">Item Name</th>
  <th class="col-description">Item Description</th>
  <th class="col-price">Price <%= f.select(:currency, @currencies, {}, {:class => 'form-control'}) %></th>
</tr>
</thead>
<tbody>
<%= f.nested_fields_for :items, wrapper_tag: :tr do |item_form| %>
  <%= render "items_edit", :item_form => item_form %>
<% end %>
</tbody>
<tfoot>
  <tr>
    <td><%= f.add_nested_fields_link :items, "", :class => "btn btn-sm btn-primary glyphicon glyphicon-plus" %></td>
    <td></td>
    <td></td>
    <td><%= f.submit "Confirm Edit", :class => "btn btn-sm btn-primary pull-right", 'title' => "Modify Event", 'data-confirm' => "Please confirm all edits. Any removal of items will be reflected in all orders. Confirm?"%></td>
  </tr>
</tfoot>
</table>

<% end %>

app/views/events/index.html.erb
<div class="maincontainer>
  <div class="title">
    <h3>Events</h3>
  </div>
  <% @events.each do |event| %>
    <%= render event, :event => event %>
  <% end %>
</div>

app/views/events/new.html.erb
<h3>Add New Event</h3>
<%= form_for @event, :url => {action: "create"}, :html => {:class => 'form-inline'} do |f| %>
<table class="table">
  <tr>
    <td><%= f.label "Event Name"%></td>
    <td><%= f.text_field :name, :class => 'form-control', :required => true %></td>
  </tr>
  <tr>
    <td><%= f.label "Location" %></td>
    <td><%= f.text_field :location, :class => 'form-control', :required => true %></td>
  </tr>
  <tr>
    <td><%= f.label "Date" %></td>
    <td><%= f.text_field :date, :class => 'form-control', :required => true, :class => 'datepicker form-control' %></td>
  </tr>
  <tr>
    <td><%= f.label "URL" %></td>
    <td><%= f.text_field :url, :class => 'form-control' %></td>
  </tr>
  <tr>
    <td><%= f.label "Currency" %></td>
    <td><%= f.select(:currency, @currencies, {}, {:class => 'form-control'}) %></td>
  </tr>
</table>
  <%= f.submit "Add Event", :class => "btn btn-sm btn-primary" %>
<% end %>

app/views/events/show.html.erb
<h3>[<%= @event.date.to_date %>] <%= @event.name %> @ <%= @event.location %></h3>

<%= render "event_menu" %>
<%= form_for @order, :url => {:action => :create, :controller => :orders }, :html => {:class => 'form-inline'} do |f| %>
<%= hidden_field_tag :event_id, @event.id %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Item Description</th>
      <th class="col-numeric">Price (<%= @event.currency %>)</th>
      <th class="col-numeric">Quantity</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.description %></td>
      <td class="col-numeric"><%= number_to_currency(item.price, unit: @event.cur_prefix, precision: @event.cur_precision ) %></td>
      <td class="col-numeric"><%= number_field_tag "order[#{item.id}][quantity]", 0, :min => 0, :class => "form-control" %></td>
      <td><%= text_field_tag "order[#{item.id}][notes]", nil, class: "form-control" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<div style="text-align:right">
  <%= f.submit "Add to Order", :class => "btn btn-sm btn-primary", :disabled => @items.empty? %>
</div>
<hr/>
<% end %>
<div>
  <h3>Attendees</h3>
  
  <ul id="eventers-list">
  <% @eventers.each do |eventer| %>
    <li id="eventer-<%= eventer.user_id %>"><%= render :template => "users/usericon", :locals => {:@user => eventer.user} %></li>
  <% end %>
  </ul>
  <%=
    btnclass = (@userevent && @userevent.going?) ? "" : " hidden"
    link_to(
      (@event.date.to_date < Date.today)? "I didn't go" : "I'm not going",
      eventer_path(:event_id=> @event.id, :user_id => current_user.id),
      :method => :put,
      :remote => true,
      :class => "btn btn-danger btn-eventer" + btnclass,
      :id => "eventer-notgoing"
    )
  %>

  <%=
    btnclass = (@userevent && @userevent.going?) ? " hidden" : ""
    link_to(
      (@event.date.to_date < Date.today)? "I went" : "I'm going",
      eventer_path(:event_id=> @event.id, :user_id => current_user.id),
      :method => :put,
      :remote => true,
      :class => "btn btn-primary btn-eventer"  + btnclass,
      :id => "eventer-going"
    )
  %>
  
</div>