config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  get 'pending' => 'users#pending'

  resources :events do
    member do
      get :all_orders
      get :agg_orders
    end
  end
  resources :eventers
  resources :orders
  resources :orderitems
  resources :users do
    member do
      get :order_list
      get :usericon
    end
  end

scope '/admin' do
  get 'approve' => 'admin#approve'
  put 'approve_user/:id' => 'admin#approve_user'
end

end

app/models/order.rb
class Order < ActiveRecord::Base
  default_scope { order('id DESC') }
  has_many :orderitems
  belongs_to :event
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :pending_user? 
  include OrdersHelper
  include EventsHelper
  include UsersHelper

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @name = get_user_name(Order.find(params[:id]).user_id)
  end

  def create
    empty_order = true
    # Find person's order for event
    order = Order.where(event_id: params[:event_id], user_id: current_user.id).first
    if order.nil?
      order = Order.new(user_id: current_user.id, event_id: params[:event_id])
      order.save
      new_order_items = params[:order]
      p new_order_items
      new_order_items.each do |new_item|
        next if new_item[1]['quantity'].to_i == 0
        empty_order = false
        new_item = Orderitem.new(order_id: order.id, item_id: new_item[0], quantity: new_item[1]['quantity'].to_i, notes: new_item[1]['notes'])
        new_item.save
      end
    else
      new_order_items = params[:order]
      new_order_items.each do |new_item|
        next if new_item[1]['quantity'].to_i == 0
        empty_order = false
        item = Orderitem.where(order_id: order.id, item_id: new_item[0])
        p item
        if item.empty?
          new_item = Orderitem.new(order_id: order.id, item_id: new_item[0], quantity: new_item[1]['quantity'].to_i, notes: new_item[1]['notes'])
          new_item.save
        else
          item.first.update_attributes(:quantity => new_item[1]['quantity'].to_i + item.first.quantity, :notes => new_item[1]['notes'])
        end
      end
    end
    if empty_order
      redirect_to root_path
    else
      redirect_to order_path(order.id)
    end
  end

  def edit
    @items = Orderitem.where(order_id: params[:id])
    @order = Order.find(params[:id])
    @event = Event.find(@order.event_id)
    redirect_to root_path if current_user.id != @order.user_id
  end

  def update
    if !params[:courier_id].nil?
      Order.find(params[:id]).update_attribute(:courier_id, params[:courier_id])

      redirect_to :back
      return
    end

    if !params[:toggle].nil?
      Order.find(params[:id]).update_attribute(:isdelivered, params[:toggle])
      if request.xhr?
        head :ok
      else
        redirect_to(:back)
      end
      return
    end

    new_order_items = params[:order]
    new_order_items.each do |new_item|
      if new_item[1]['quantity'].to_i == 0
        Orderitem.where(order_id: params[:id], item_id: new_item[0]).destroy_all
        next
      end
      item = Orderitem.where(order_id: params[:id], item_id: new_item[0])
      item.first.update_attributes!(:quantity => new_item[1]['quantity'].to_i, :notes => new_item[1]['notes'])
    end
    if Orderitem.where(order_id: params[:id]).empty?
      puts "destroying order"
      Order.find(params[:id]).destroy
      redirect_to order_list_user_path(current_user.id)
    else
      redirect_to order_path(params[:id])
    end
  end

  def destroy
    Orderitem.where(order_id: params[:id]).destroy_all
    Order.find(params[:id]).destroy

    redirect_to order_list_user_path(current_user.id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def get_order_total(order_id)
    items = Orderitem.where(order_id: order_id)
    total = 0
    items.each do |item|
      total = total + (Item.find(item.item_id).price * item.quantity)
    end
    total
  end

  def get_item_name(id)
    Item.find(id).name
  end

  def get_item_description(id)
    Item.find(id).description
  end

  def get_item_price(id)
    Item.find(id).price
  end

  def toggle_purchase_button(orderitem)
    if orderitem.ispurchased?
      link_to(
        content_tag(:span, nil, :class => "glyphicon glyphicon-ok"),
        orderitem_path(orderitem.id, :toggle => "false"),
        :method => :put,
        :remote => true,
        :class => "purchase purchase-true btn btn-sm btn-primary",
        :id => orderitem.id
      )
    else
      link_to(
        content_tag(:span, nil, :class => "glyphicon glyphicon-plus"),
        orderitem_path(orderitem.id, :toggle => "true"),
        :method => :put,
        :remote => true,
        :class => "purchase purchase-false btn btn-sm btn-danger",
        :id => orderitem.id
      )
    end
  end
end

app/views/orders/_agg_item.html.erb
<div class="item-order row">
  <div class="col-sm-1 hidden-xs">
    <%= toggle_purchase_button orderitem %>
  </div>  
  <div class="col-sm-3"><%= link_to get_user_name(orderitem.order.user_id), order_path(orderitem.order.id) %></div>
  <div class="col-sm-1">x <%= orderitem.quantity %></div>
  <div class="col-xs-6"><%= orderitem.notes %></div>
  <div class="col-xs-1 visible-xs">
    <%= toggle_purchase_button orderitem %>
  </div>  
</div>

app/views/orders/_item.html.erb
<div class="row order-item">
  <div class="col-sm-1 hidden-xs">
    <%= toggle_purchase_button orderitem %>
  </div>
  <div class="col-sm-11 order-content">
    <div>
      <div class="col-sm-2">
        <p class="label-item visible-xs">Item</p>
        <p class="order-data-item"><%= orderitem.item.name %></p>
      </div>
      <div class="col-sm-3">
        <p class="label-item visible-xs">Description</p>
        <p class="data-item"><%= orderitem.item.description %></p>
      </div>
      <div class="item-price col-sm-2">
        <p class="label-item visible-xs">Price</p>
        <p class="data-item"><%= number_to_currency(orderitem.item.price, unit: orderitem.order.event.cur_prefix, precision: orderitem.order.event.cur_precision ) %></p>
        </div>
      <div class="item-quantity col-sm-2">
        <p class="label-item visible-xs">Quantity</p>
        <p class="data-item"><%= orderitem.quantity %></p>
      </div>
      <div class="item-total col-sm-2">
        <p class="label-item visible-xs">Total</p>
        <p class="data-item"><%= number_to_currency(orderitem.quantity * orderitem.item.price, unit: orderitem.order.event.cur_prefix, precision: orderitem.order.event.cur_precision ) %></p>
      </div>
    </div>
    <div class="col-sm-11">
      <%= orderitem.notes %>
    </div>
    <div class="col-xs-12 visible-xs">
      <%= toggle_purchase_button orderitem %>
    </div>
  </div>
</div>

app/views/orders/_item_header.html.erb
<thead>
  <th>Item Name</th>
  <th>Item Description</th>
  <th>Notes</th>
  <th>Unit Price</th>
  <th>Quanitity</th>
  <th>Total Price</th>
  <th>Purchased</th>
</thead>

app/views/orders/_order_total.html.erb
<div class="order-total col-sm-6">
  <%= format_price(order.event_id, get_order_total(order['id'])) %>
</div>
<div class="col-sm-6">
    <% if order.isdelivered %>
    <%= link_to order_path(order.id, :toggle => "false"), :method => :put, :class => "btn btn-sm btn-success" do %><span class="glyphicon glyphicon-plane"></span><% end %>
    <% else %>
    <%= link_to order_path(order.id, :toggle => "true"), :method => :put, :class => "btn btn-sm btn-danger" do %><span class="glyphicon glyphicon-plane"></span><% end %>
    <% end %>
</div>

app/views/orders/edit.html.erb
<h3>Order: <%= params[:id] %></h3>
<ul>
<li><%= link_to @event.name, event_path(@event.id) %></li>
</ul>
<%= form_for @order, :url => {:action => :update, :controller => :orders } do |f| %>
<table class="table table-striped">
<tr>
  <th>Item Name</th>
  <th>Item Description</th>
  <th>Unit Price</th>
  <th>Quanitity</th>
  <th>Notes</th>
</tr>
<% @items.each do |item| %>
  <tr>
  <td><%= get_item_name(item.item_id) %></td>
  <td><%= get_item_description(item.item_id) %></td>
  <td><%= get_item_price(item.item_id) %></td>
  <td><%= number_field_tag "order[#{item.item_id}][quantity]", item['quantity'], :min => 0 %></td>
  <td><%= text_field_tag "order[#{item.item_id}][notes]", item['notes'] %></td>
  </tr>
<% end %>
<tr>
  <td/>
  <td/>
  <td/>
  <td/>
  <td><%= f.submit "Edit Order", :class => "btn btn-sm btn-primary pull-right" %></td>
</table>
<% end %>

app/views/orders/index.html.erb
<h3>All Orders</h3>
<table class="table">
<tr>
  <th>Order Number</th>
  <th>Who</th>
  <th>Event Name</th>
  <th>Price</th>
  <th></th>
</tr>
<% @orders.each do |order| %>
<tr>
  <td><%= order.id %></td>
  <td><%= link_to get_user_name(order.user_id), order_list_user_path(order.user_id) %></td>
  <td><%= link_to get_event_name(order.event_id), event_path(order.event_id) %></td>
  <td><%= get_order_total(order.id) %></td>
  <td><%= link_to "View Order", order_path(order.id), :class => "btn-sm btn-primary" %></td>
</tr>
<% end %>
</table>

app/views/orders/list.html.erb
<h3>My Orders</h3>
<table class="table">
<tr>
  <th>Event Name</th>
  <th>Total Price</th>
</tr>
<% @orders.each do |order| %>
<tr>
  <td><%= link_to '>View Order', :action => :show, :id => order.id %></td>
  <td><%= event.name %></td>
  <td><%= event.location %></td>
  <td>(Going/Not Going)</td>
</tr>
<% end %>
</table>

app/views/orders/show.html.erb
<h3>Order: <%= params[:id] %></h3>
<ul>
<li><%= @name %></li>
<li><%= link_to @order.event.name, event_path(@order.event.id) %></li>
<li>Courier: <%= get_user_name @order.courier_id %></li>
</ul>
<table class="table table-striped">
<%= render "item_header" %>
<% @order.orderitems.each do |orderitem| %>
<%= render "item", :orderitem => orderitem %>
<% end %>
<%= render "order_total", :order_id => @order.id, :order => @order %>
</table>

<% if @order.courier_id != current_user.id %>
    <%= link_to "Assign Self as Handler", order_path(params[:id], :courier_id => current_user.id), :method => :put, :class => "btn btn-sm btn-primary" %>
<% else %>
   <%= link_to "Unassign Self as Handler", order_path(params[:id], :courier_id => 0), :method => :put, :class => "btn btn-sm btn-primary" %>
<% end  %>


<%= link_to "Edit Order", edit_order_path(params[:id]), :class => "btn btn-sm btn-primary" if current_user.id == @order.user_id %>
<%= link_to "Delete Order", order_path(params[:id]), :method => :delete, :class => "btn btn-sm btn-danger", 'title' => "Delete Order", 'data-confirm' => "Are you sure you want to delete this order?" if current_user.id == @order.user_id %>