config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  get 'pending' => 'users#pending'

  resources :events do
    member do
      get :all_orders
      get :agg_orders
    end
  end
  resources :eventers
  resources :orders
  resources :orderitems
  resources :users do
    member do
      get :order_list
      get :usericon
    end
  end

scope '/admin' do
  get 'approve' => 'admin#approve'
  put 'approve_user/:id' => 'admin#approve_user'
end

end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">HPT Courier Services</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav ">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Events <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "List Events", events_path %></li>
          <li><%= link_to "Add Events", new_event_path if user_signed_in? %></li>
        </ul>
      </li>    
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Orders <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "My Orders", order_list_user_path(current_user.id) if user_signed_in? %></li>
          <li><%= link_to "All Orders", orders_path %></li>
        </ul>
      </li>    
      <li>
        <a href="/users">Users</a>
      </li>
      <% if current_user.try(:is_admin?) %>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Approve Users", approve_path %></li>
        </ul>
      </li>  
      <% end %>
    </ul>  
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.name,  edit_user_registration_path %></a></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Register",  new_user_registration_path %></a></li>
        <li><%= link_to "Sign In",  new_user_session_path %></a></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HPT Courier Services</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<%= render "layouts/menu" %>
<div class="container-fluid">
  <%= yield %>
</div>
</body>
</html>